### ISSUE TITLE
styles Second argument passed into a variable object the type cannot be determined

### ISSUE THREAD

**Issue by fslflame** [styils/styils#292]
![image](https://github.com/styils/styils/assets/101857530/a3184d00-e79e-4be0-8509-5ff11bb8864e)

**Comment by fslflame** [comment]
![image](https://github.com/styils/styils/assets/101857530/9725bbc7-935e-4388-950d-e210d43bed71)
The example is wrong. It's vars

**Comment by zoy-l** [comment]
> ![image](https://private-user-images.githubusercontent.com/101857530/322005464-9725bbc7-935e-4388-950d-e210d43bed71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDA3MDYsIm5iZiI6MTcxMzE0MDQwNiwicGF0aCI6Ii8xMDE4NTc1MzAvMzIyMDA1NDY0LTk3MjViYmM3LTkzNWUtNDM4OC05NTBkLWUyMTBkNDNiZWQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMDIwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjc5ZGU5OTFjNmFhNzQ1ZTZkNTc5NDQzNzQ3ZGNiMDU2MmI0YWY1MjFiZTg2YTY1Y2UyNTI1NmUyMDc2M2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.27KQdoGZx4MDWDX5YifjeWePUdYhf2a5BWsS5rLfcrM) The example is wrong. It's vars

 need to add const to the returned object, otherwise TypeScript cannot infer the specific value type.
```ts
function getStyle(){
   return {...} as const
}
```

**Comment by fslflame** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/101857530/322005464-9725bbc7-935e-4388-950d-e210d43bed71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDA3MDYsIm5iZiI6MTcxMzE0MDQwNiwicGF0aCI6Ii8xMDE4NTc1MzAvMzIyMDA1NDY0LTk3MjViYmM3LTkzNWUtNDM4OC05NTBkLWUyMTBkNDNiZWQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMDIwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjc5ZGU5OTFjNmFhNzQ1ZTZkNTc5NDQzNzQ3ZGNiMDU2MmI0YWY1MjFiZTg2YTY1Y2UyNTI1NmUyMDc2M2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.27KQdoGZx4MDWDX5YifjeWePUdYhf2a5BWsS5rLfcrM)这个例子是错误的。这是变量
> 
> 需要给返回的对象添加const，否则TypeScript无法推断出具体的值类型。
> 
> ```ts
> function getStyle(){
>    return {...} as const
> }
> ```

Why do I need to infer to specific types that the source code has done internally?

**Comment by zoy-l** [comment]
When using `vars`, which relies on `value` rather than `key`, the actual type obtained when using a variable is ```{ gridTemplateColumns: string }```. Therefore, it's not possible to obtain the type of a value like $grid-cols. When adding const, the type obtained is ```{readonly gridTemplateColumns: "$grid-cols" }```.

**Comment by zoy-l** [comment]
I'm going to close this issue, feel free to reopen if there are any other issues
